// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laohaldusprojekt.Data;

#nullable disable

namespace laohaldusprojekt.Migrations
{
    [DbContext(typeof(LaohaldusContext))]
    [Migration("20260527120327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("laohaldusprojekt.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Hind")
                        .HasColumnType("float");

                    b.Property<string>("Kategooria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kogus")
                        .HasColumnType("int");

                    b.Property<string>("TooteNimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hind = 3.5499999999999998,
                            Kategooria = "Liha- ja kalatooted",
                            Kogus = 4,
                            TooteNimi = "Lihapihvid, MAKS&MOORITS"
                        },
                        new
                        {
                            Id = 2,
                            Hind = 5.0,
                            Kategooria = "Liha- ja kalatooted",
                            Kogus = 2,
                            TooteNimi = "Kodune šašlõkk"
                        },
                        new
                        {
                            Id = 3,
                            Hind = 3.1899999999999999,
                            Kategooria = "Piimatooted",
                            Kogus = 5,
                            TooteNimi = "Juustupulgad Pik-Nik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
